name: Deploy API to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    needs: [ci]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Login to Vercel
        run: vercel login

      - name: Deploy API
        run: vercel --prod
